import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isLoaded, isSignedIn } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-200">
        <div className="text-2xl">Change Change</div>
        {isSignedIn && (
          <div>
            <div>{`Hello, ${user.fullName ? user.fullName : "You"}`}</div>
            <SignOutButton />
          </div>
        )}
        {!isSignedIn && (
          <div className="flex justify-center">
            <SignInButton />
          </div>
        )}
        <div>Notion access test</div>
      </main>
    </>
  );
};

export default Home;
